name: Deploy Vite React App to EC2

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

    - name: Deploy to EC2
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
          cd ~/react-app || git clone https://github.com/prakash32536/ShopHub.git ~/react-app
          cd ~/react-app
          git pull origin main

          docker rm -f vite-react || true
          docker build -t vite-react .
          docker run -d -p 3000:80 --name vite-react vite-react
        EOF
